// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(BSDBContext))]
    [Migration("20211213164228_History")]
    partial class History
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.BrainDbDTO", b =>
                {
                    b.Property<int>("BrainDbDTOId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameConfigDbDtoId")
                        .HasColumnType("int");

                    b.Property<string>("GameName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Turn")
                        .HasColumnType("int");

                    b.HasKey("BrainDbDTOId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Domain.GameConfigDbDTO", b =>
                {
                    b.Property<int>("GameConfigDbDtoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BoardHeight")
                        .HasColumnType("int");

                    b.Property<int>("BoardWidth")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipConfigs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipPlacement")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameConfigDbDtoId");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("Domain.MoveHistoryDTO", b =>
                {
                    b.Property<int>("MoveHistoryDTOId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrainDbDTOId")
                        .HasColumnType("int");

                    b.Property<string>("Redo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Undo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MoveHistoryDTOId");

                    b.ToTable("History");
                });

            modelBuilder.Entity("Domain.PlayerDbDTO", b =>
                {
                    b.Property<int>("PlayerDbDTOId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrainDbDTOId")
                        .HasColumnType("int");

                    b.Property<string>("EnemyBoard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MyBoard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ships")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerDbDTOId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Domain.Settings", b =>
                {
                    b.Property<int>("SettingsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("saveToDB")
                        .HasColumnType("bit");

                    b.HasKey("SettingsID");

                    b.ToTable("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
